# Generated by Django 3.0.3 on 2022-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genus', models.CharField(blank=True, max_length=100)),
                ('plant_img', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('color', models.ManyToManyField(blank=True, to='plants.Color')),
            ],
        ),
    ]
