# Generated by Django 3.0.3 on 2022-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='color',
        ),
        migrations.AddField(
            model_name='plant',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
